name: demo

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
          
      - name: Upgrade pip and install  dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python -m pip install --upgrade pip
          pip install setuptools  # Ensure setuptools is installed first
          pip install -r requirements.txt --upgrade

      - name: Install additional dependencies
        run: |
          pip install sphinx pandoc
      - name: Sphinx build
        run: |
          sphinx-build src/docs src/docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/docs/_build/
          force_orphan: true
