name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: make the sphinx docs
        run: |
          make -C src/docs clean 
          # sphinx-apidoc -f -o docs/source . -H Test -e -t docs/source/_templates
          make -C src/docs html
          

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd src/docs/_build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Push docs to gh-pages
        run: |
          git branch -M gh-pages
          git push --force origin gh-pages

